### ISSUE TITLE
一旦通しで、tokenizerからexecの部分までを作るます

### ISSUE THREAD

**Issue by ninomae42** [ninomae42/minishell#14]
### 概要
- 方針変更をする。
- tokenizer、parser, expand, pipeline, execの全部をモジュールとして別々に開発する方針だったが、細かい挙動の部分などの確認が必要となってきた。
- tokenizerからexecまで通しで実行できるminishellのバイナリを作って、bashとdiffを取る方針に変更する

以下にTODOを列挙したが、後ほどそれぞれをイシューに切り出して実装を進める

### TODO
- [x] wordだけで構成されたコマンド文字列を実行する(絶対パス)
- [x] #20
- [ ] wordとsingle quoteで構成されたコマンド文字列を実行する
- [ ] wordとdouble quoteで構成されたコマンド文字列を実行する
- [ ] input redirectとwordで構成されたコマンド文字列を実行する
- [ ] output redirectとwordで構成されたコマンド文字列を実行する
- [ ] output redirect appendとwordで構成されたコマンド文字列を実行する
- [ ] redirect + quotation + wordで構成されたコマンド文字列を実行する
- [ ] pipeline + wordで構成されたコマンド文字列を実行する
- [ ] pipeline + word + quotationで構成されたコマンド文字列を実行する
- [ ] pipeline + word + quotation + redirectで構成されたコマンド文字列を実行する
